name       : python-geoip
version    : 0.2.7
release    : 6
source     :
    - https://pypi.python.org/packages/source/p/pygeoip/pygeoip-0.2.7.tar.gz : 7c4e7b5913bf3adfc0240bde5183e37a921ded2b44bbf29531a761b83a7427fd
license    : LGPL-3.0
component  : programming.python
summary    : Python API for GeoIP lookups
description: |
    Pure Python GeoIP API # The API is based on [MaxMind's C-based Python API](http://dev.maxmind.com/geoip/downloadable#Python-5), but the code itself is ported from the [Pure PHP GeoIP API](http://pear.php.net/package/Net_GeoIP) by Jim Winstead and Hans Lellelid.
builddeps  :
    - pkgconfig(python-3.5)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
    # Install data files
    install -D -m 00644 $pkgfiles/City.dat $installdir/usr/share/GeoIP/City.dat
    install -D -m 00644 $pkgfiles/Country.dat $installdir/usr/share/GeoIP/Country.dat
