name       : python-geoip
version    : 0.3.2
release    : 10
source     :
    - https://files.pythonhosted.org/packages/ed/65/bb86312b064a6e79c82965202f239850008dbcc9bb24bd0d0bfc7b7bea0b/pygeoip-0.3.2.tar.gz : f22c4e00ddf1213e0fae36dc60b46ee7c25a6339941ec1a975539014c1f9a96d
license    : LGPL-3.0
component  : programming.python
summary    : Python API for GeoIP lookups
description: |
    Pure Python GeoIP API # The API is based on [MaxMind's C-based Python API](http://dev.maxmind.com/geoip/downloadable#Python-5), but the code itself is ported from the [Pure PHP GeoIP API](http://pear.php.net/package/Net_GeoIP) by Jim Winstead and Hans Lellelid.
builddeps  :
    - pkgconfig(python3)
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
    # Install data files
    install -D -m 00644 $pkgfiles/City.dat $installdir/usr/share/GeoIP/City.dat
    install -D -m 00644 $pkgfiles/Country.dat $installdir/usr/share/GeoIP/Country.dat
